#!/bin/sh

set -e

GIT_SSL_NO_VERIFY=1 git pull origin

[ -f ./VERSION ] || (echo "file VERSION containing current version is needed" && exit 1)
[ -f ./setup.py ] || (echo "file setup.py is required" && exit 1)
[ -z $USERNAME ] && (echo "env var USERNAME is required" && exit 1)
[ -z $PASSWORD ] && (echo "env var PASSWORD is required" && exit 1)

python setup.py sdist bdist_wheel

python -m twine upload -u $USERNAME -p $PASSWORD  dist/*

