#!/bin/sh

test -f ./VERSION || (echo "file VERSION containing current version is needed" && exit 1)
test -f ./setup.py || (echo "file setup.py is needed" && exit 1)

python setup.py sdist bdist_wheel

python -m twine upload -u $USERNAME -p $PASSWORD  dist/*

